cainfo: ""
capath: ""
direct-domains: []
dns: []
fast-fail-regexps: []
log-stats: 0
logfile: ""
max-logsize: 0
metrics-address: "localhost:0"
no-autodetect: false
no-proxy-caching: false
no-remove-colliding-tunnels: false
no-ssl-bump-domains: []
pac: ""
pidfile: ""
proxy: ""
proxy-tunnel: false
proxy-userpwd: ""
readyfile: ""
rest-url: "https://saucelabs.com/rest/v1"
scproxy-port: 0
scproxy-read-limit: 0
scproxy-write-limit: 0
se-port: 0
shared-tunnel: true
tunnel-domains: []
verbose: 0
vm-version: ""
