name: Docker swarm
on:
  pull_request:
  workflow_dispatch:
jobs:
  runner-job:
    runs-on: ubuntu-latest
    services:
      chrome:
        image: selenium/node-chrome:4.0.0-beta-3-prerelease-20210321
        volumes:
          - /dev/shm:/dev/shm
      firefox:
        image: selenium/node-firefox:4.0.0-beta-3-prerelease-20210321
        volumes:
          - /dev/shm:/dev/shm

      selenium-hub:
        image: selenium/hub:4.0.0-beta-1-20210215
        ports:
          - "4442:4442"
          - "4443:4443"
          - "4444:4444"
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          bash installDependencies.sh
      - name: wait for hub
        run: |
          bash waitForSeleniumGrid.sh
      - name: run watir test
        run: |
          ruby $GITHUB_WORKSPACE/tests/watir\-example.rb
      # - name: run webdriver test
      #   run: |
      #     node $GITHUB_WORKSPACE/tests/webdriver\-example.js
