name: Docker swarm
on:
  pull_request:
  workflow_dispatch:
jobs:
  runner-job:
    runs-on: ubuntu-latest
    services:
      chrome:
        image: selenium/node-chrome:4.0.0-beta-1-20210215
        volumes:
          - /dev/shm:/dev/shm

      selenium-hub:
        image: selenium/hub:4.0.0-beta-1-20210215
        ports:
          - "4442:4442"
          - "4443:4443"
          - "4444:4444"
    steps:
      - uses: actions/checkout@v2
      - name: install gems
        run: |
          echo $(bash installGems.sh)
      - name: run test
        run: |
          echo $(ruby $GITHUB_WORKSPACE/tests/watir\-example.rb)
  # edge:
  #   image: selenium/node-edge:4.0.0-beta-1-20210215
  #   volumes:
  #     - /dev/shm:/dev/shm
  #   environment:
  #     - SE_EVENT_BUS_HOST=selenium-hub
  #     - SE_EVENT_BUS_PUBLISH_PORT=4442
  #     - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  #   deploy:
  #     replicas: 1
  #   entrypoint: bash -c 'SE_OPTS="--host $$HOSTNAME" /opt/bin/entry_point.sh'

  # firefox:
  #   image: selenium/node-firefox:4.0.0-beta-1-20210215
  #   volumes:
  #     - /dev/shm:/dev/shm
  #   environment:
  #     - SE_EVENT_BUS_HOST=selenium-hub
  #     - SE_EVENT_BUS_PUBLISH_PORT=4442
  #     - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  #     - HUB_HOST=selenium-hub
  #   depends_on:
  #     - selenium-hub
  #   links:
  #     - selenium-hub:hub
  #   networks:
  #     - selenium_network
  #   deploy:
  #     replicas: 1
  #   entrypoint: bash -c 'SE_OPTS="--host $$HOSTNAME" /opt/bin/entry_point.sh'

  # opera:
  #   image: selenium/node-opera:4.0.0-beta-1-20210215
  #   volumes:
  #     - /dev/shm:/dev/shm
  #   environment:
  #     - SE_EVENT_BUS_HOST=selenium-hub
  #     - SE_EVENT_BUS_PUBLISH_PORT=4442
  #     - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  #   deploy:
  #     replicas: 1
  #   entrypoint: bash -c 'SE_OPTS="--host $$HOSTNAME" /opt/bin/entry_point.sh'

  # swarm:
  #   name: Run docker swarm
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: ./actions/selenium-grid-action
  #   ports:
  #     - 4444:4444
