name: Windows wdio workflow
on:
  pull_request:
  workflow_dispatch:
jobs:
  run-job:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir -p tests\artifacts\
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: start up hub
        run: |
          cd cucumberJs
          npx wdio run windows_wdio.conf.js
