name: Windows workflow
on:
  pull_request:
  workflow_dispatch:
jobs:
  run-job:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir -p tests\artifacts\
      - uses: actions/setup-java@v2
        with:
          distribution: "adopt" # See 'Supported distributions' for available options
          java-version: "11"
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: start up hub
        run: |
          dir
          cd scripts\
          .\windows_start.sh &
          curl http://localhost:4444/wd/hub
          Write-Output 'plz work...'

      - name: run webdriver scripts
        run: |
          cd scripts\
          Write-Output 'plz work...'
          .\runNode.sh
