name: Windows workflow
on:
  pull_request:
  workflow_dispatch:
jobs:
  run-job:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir -p tests\artifacts\
      - uses: actions/setup-java@v2
        with:
          distribution: "adopt" # See 'Supported distributions' for available options
          java-version: "11"
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: set ie in path
        run: |
          echo "C:\directory\to\add\to\path" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          # dir
          # cd
          # set PATH=%PATH%;D:\a\selenium-grid-POC\selenium-grid-POC
      - name: start up hub and run tests
        run: |
          cd scripts\
          java -version
          java -jar selenium-server-standalone.jar &
          java -jar -Dwebdriver.ie.driver="IEDriver.exe" -Dwebdriver.gecko.driver="geckodriver.exe" -Dwebdriver.chrome.driver="chromedriver.exe" selenium-server-standalone.jar -role node -nodeConfig node.json &
          cd ..
          cd tests\
          npm install
          curl http://localhost:4444/wd/hub
          node windows-webdriver.js


      # - name: run webdriver scripts
      #   run: |
      #     curl http://www.google.com
      #     curl http://localhost:4444/wd/hub
      #     curl http://127.0.0.1:4444/wd/hub
          
