name: Windows workflow
on:
  pull_request:
  workflow_dispatch:
jobs:
  run-job:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir -p tests\artifacts\
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '11'
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: start up hub
        run: |
          dir
          cd tests\
          npm install
          npx selenium-standalone install
          npx selenium-standalone start &
          Start-Sleep -s 30
          curl http://localhost:4444/wd/hub &
      - name: run tests
        run: |
          cd tests\
          curl http://localhost:4444/wd/hub
          node windows-webdriver.js

      # - name: run webdriver scripts
      #   run: |
      #     curl http://www.google.com
      #     curl http://localhost:4444/wd/hub
      #     curl http://127.0.0.1:4444/wd/hub
